- hosts: aws_vps
  tasks:
    - name: Pull latest code
      git:
        repo: 'https://github.com/zeroLR/discord-bot-ai-agent.git'
        dest: /home/ubuntu/discord-bot
        version: main
        force: yes

    - name: Copy .env file
      copy:
        src: ../.env
        dest: /home/ubuntu/discord-bot/.env
        owner: ubuntu
        mode: '0600'

    - name: Build and restart docker-compose
      shell: |
        cd /home/ubuntu/discord-bot
        sudo docker compose pull
        sudo docker compose up -d --build