name: Deploy to AWS VPS

on:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ansible
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Validate deployment configuration
        run: |
          # Check if deploy directory exists and has required files
          test -f deploy/deploy.yml
          test -f deploy/inventory.ini
          # Validate Ansible playbook syntax
          ansible-playbook --syntax-check deploy/deploy.yml

      - name: Run tests
        run: |
          # Run existing tests to ensure code quality
          PYTHONPATH=. python util/test_transform_response_content.py

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Ansible
        run: pip install ansible

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_VPS_SSH_KEY }}

      - name: Write .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i deploy/inventory.ini deploy/deploy.yml
