name: Deploy to AWS VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible
        run: pip install ansible

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.AWS_VPS_SSH_KEY }}

      - name: Write .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i deploy/inventory.ini deploy/deploy.yml
